name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: "ubuntu-latest"
            extension: ""
            platformAgnosticChecks: true
          - os: "windows-latest"
            extension: ".exe"
            extraArgs: ""
    steps:
      - uses: actions/checkout@v2

      - name: "Make build"
        run: make build
      
      - name: "Make prepare-release"
        run: make prepare-release
        if: ${{ fromJSON(matrix.config.os == 'ubuntu-latest') }}

      - name: "Make prepare-release-win"
        run: make prepare-release-win
        if: ${{ fromJSON(matrix.config.os == 'windows-latest') }}

      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
          files: |
            files/*.txt
            dansay-rs-unix.tar.gz
            dansay-rs-win.tar.gz